### ISSUE TITLE
cannot find rates library

### ISSUE THREAD

**Issue by odroidodroid** [facebookresearch/pal#1]
can you share the library "rates" referred at README.md? 
I want to implement the code.

Thanks

YoungJinKim

**Comment by VivienCabannes** [comment]
Thank you for your interest.
The repo should be soon online, in the meantime you can email me at vivc@meta.com, so that I send you a copy of the repo.
Best regards
Vivien

**Comment by VivienCabannes** [comment]
It is now online https://github.com/facebookresearch/rates
